# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Genre1',
            field=models.CharField(default='Action', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='Genre2',
            field=models.CharField(default='Romance', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='Genre3',
            field=models.CharField(default='Thriller', max_length=20),
        ),
    ]
