# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_auto_20180331_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='Genre1',
            field=models.ForeignKey(default='Action', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='finder.Genre'),
        ),
    ]
