# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0003_auto_20180331_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Genre1',
            field=models.CharField(choices=[('Action', 'Action'), ('Thriller', 'Thriller'), ('Comedy', 'Comedy')], default='Action', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='Genre2',
            field=models.CharField(choices=[('Action', 'Action'), ('Thriller', 'Thriller'), ('Comedy', 'Comedy')], default='Romance', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='Genre3',
            field=models.CharField(choices=[('Action', 'Action'), ('Thriller', 'Thriller'), ('Comedy', 'Comedy')], default='Thriller', max_length=20),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
