# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0004_auto_20180331_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Genre1',
            field=models.CharField(choices=[('action', 'action'), ('romance', 'romance'), ('comedy', 'comedy'), ('crime', 'crime'), ('horror', 'horror'), ('sci-fi', 'sci-fi')], default='Action', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='Genre2',
            field=models.CharField(choices=[('action', 'action'), ('romance', 'romance'), ('comedy', 'comedy'), ('crime', 'crime'), ('horror', 'horror'), ('sci-fi', 'sci-fi')], default='Romance', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='Genre3',
            field=models.CharField(choices=[('action', 'action'), ('romance', 'romance'), ('comedy', 'comedy'), ('crime', 'crime'), ('horror', 'horror'), ('sci-fi', 'sci-fi')], default='Thriller', max_length=20),
        ),
    ]
