# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0005_auto_20180331_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.IntegerField()),
                ('u_movie_id', models.IntegerField()),
                ('u_rating', models.FloatField(default=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default=None, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Hostels',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
