# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0006_auto_20180401_0739'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='RollNo',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='usermovies',
            old_name='u_id',
            new_name='c_id',
        ),
        migrations.RenameField(
            model_name='usermovies',
            old_name='u_movie_id',
            new_name='c_movie_id',
        ),
        migrations.RenameField(
            model_name='usermovies',
            old_name='u_rating',
            new_name='c_rating',
        ),
    ]
