# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-01 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0007_auto_20180401_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_title', models.CharField(default=None, max_length=100)),
                ('m_year', models.CharField(default=None, max_length=200)),
                ('m_url', models.CharField(default=None, max_length=2000)),
                ('m_dir', models.CharField(max_length=200)),
                ('m_uvote', models.IntegerField(default=120)),
                ('m_rvote', models.IntegerField(default=20)),
                ('m_duration', models.CharField(default=None, max_length=50)),
                ('m_description', models.CharField(default='NICE', max_length=3000)),
                ('m_urating', models.FloatField(default=10)),
                ('m_rrating', models.FloatField(default=100)),
            ],
        ),
    ]
