# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-01 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0008_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='id',
        ),
        migrations.AddField(
            model_name='movie',
            name='m_genre',
            field=models.CharField(default='Action', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='m_title',
            field=models.CharField(default=None, max_length=100, primary_key=True, serialize=False),
        ),
    ]
