# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-01 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0009_auto_20180401_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='m_rrating',
            field=models.IntegerField(default=100),
        ),
    ]
