# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0010_auto_20180401_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermovies',
            name='c_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='im_link',
            field=models.CharField(default='https://www.alaskapacific.edu/wp-content/uploads/2015/11/placeholder_profile_photo-200x200.png', max_length=1000),
        ),
        migrations.AddField(
            model_name='usermovies',
            name='c_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
