# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-12 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0012_auto_20180411_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('re_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('re_password', models.CharField(max_length=100)),
                ('re_weightage', models.IntegerField(default=10)),
            ],
        ),
    ]
