# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-14 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0016_watchtime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='watchtime',
        ),
    ]
