# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-14 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0017_delete_watchtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='watchtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_time', models.IntegerField(default=1)),
            ],
        ),
    ]
