# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0019_direcmovies_director'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviewer',
        ),
        migrations.AddField(
            model_name='customer',
            name='reviewer',
            field=models.IntegerField(default=0),
        ),
    ]
